### ISSUE TITLE
ESP32 compatibility 

### ISSUE THREAD

**Issue by GreatResistance** [retrospy/OPT4048#4]
Is it possible to make the ESP32 ( with Arduino IDE) working with this library too? 
Version 1.1 works fine with "ESP32 Devkit C", but version V1.2 and above I become error messages if I try to compile it.

**Comment by GreatResistance** [comment]
Error messages:

...Arduino\libraries\OPT4048\src\OPT4048.cpp:244:128: note:   deduced conflicting types for parameter 'const _Tp' ('double' and 'float')
  retval.B = min(1.0, max(0.0, (*CompandingFunc)(xyz.X * XYZ_to_RGB[2][0] + xyz.Y * XYZ_to_RGB[2][1] + xyz.Z * XYZ_to_RGB[2][2])));
                                                                                                                                



...arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\bits\stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
c:\Users\andras.homoki\Documents\Arduino\libraries\OPT4048\src\OPT4048.cpp:244:128: note:   deduced conflicting types for parameter 'const _Tp' ('double' and 'float')



arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\bits\stl_algo.h:3462:5: note:   template argument deduction/substitution failed:
c:\Users\andras.homoki\Documents\Arduino\libraries\OPT4048\src\OPT4048.cpp:244:128: note:   mismatched types 'std::initializer_list<_Tp>' and 'double'
  retval.B = min(1.0, max(0.0, (*CompandingFunc)(xyz.X * XYZ_to_RGB[2][0] + xyz.Y * XYZ_to_RGB[2][1] + xyz.Z * XYZ_to_RGB[2][2])));
                                                                                                                                




It would be great if you could get it work :-) Thank you!

**Comment by zoggins** [comment]
1.9 should fix your problem.  I just pushed it, will take a little while to get the Arduino servers.

**Comment by GreatResistance** [comment]
A big-big thank you! :-)
